// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB1oKp1I-xp25O24DUvFOhukTauZ2xURY',
    appId: '1:950705029475:web:3bcdc7d31146b39b619356',
    messagingSenderId: '950705029475',
    projectId: 'mmtd-9cedf',
    authDomain: 'mmtd-9cedf.firebaseapp.com',
    databaseURL: 'https://mmtd-9cedf-default-rtdb.firebaseio.com',
    storageBucket: 'mmtd-9cedf.appspot.com',
    measurementId: 'G-2X57372GZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBvKAPirAstsBZw2VFsGOjZdto_s7kM9Q',
    appId: '1:950705029475:android:34d712d20f2a7d5c619356',
    messagingSenderId: '950705029475',
    projectId: 'mmtd-9cedf',
    databaseURL: 'https://mmtd-9cedf-default-rtdb.firebaseio.com',
    storageBucket: 'mmtd-9cedf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5NbyJeyiXtfLtWt2WHUapIwLfQIX3EE',
    appId: '1:950705029475:ios:3ec1450875974753619356',
    messagingSenderId: '950705029475',
    projectId: 'mmtd-9cedf',
    databaseURL: 'https://mmtd-9cedf-default-rtdb.firebaseio.com',
    storageBucket: 'mmtd-9cedf.appspot.com',
    androidClientId: '950705029475-ddqmk3l8th8e4ifjm7b2lud1qncg33ii.apps.googleusercontent.com',
    iosClientId: '950705029475-mq8420sgfq5qvu9cjgah8uaql304q52c.apps.googleusercontent.com',
    iosBundleId: 'com.monitt5.garden',
  );
}
